version: '3.8'

services:
  consul:
    image: consul:1.15
    container_name: consul-server
    ports:
      - "8500:8500"  # Web UI
      - "8600:8600/udp"
      - "8600:8600"
    command: agent -dev -client=0.0.0.0
